In [3]:
import pandas as pd
import numpy as np
pd.set_option('display.max_columns', 500)

In [4]:
df = pd.read_excel('default_of_credit_card_clients.xls')
df.head()

ID  LIMIT_BAL  SEX  EDUCATION  MARRIAGE  AGE PAY_1  PAY_2  \
0  798fc410-45c1      20000    2          2         1   24     2      2   
1  8a8c8f3b-8eb4     120000    2          2         2   26    -1      2   
2  85698822-43f5      90000    2          2         2   34     0      0   
3  0737c11b-be42      50000    2          2         1   37     0      0   
4  3b7f77cc-dbc0      50000    1          2         1   57    -1      0   

   PAY_3  PAY_4  PAY_5  PAY_6  BILL_AMT1  BILL_AMT2  BILL_AMT3  BILL_AMT4  \
0     -1     -1     -2     -2       3913       3102        689          0   
1      0      0      0      2       2682       1725       2682       3272   
2      0      0      0      0      29239      14027      13559      14331   
3      0      0      0      0      46990      48233      49291      28314   
4     -1      0      0      0       8617       5670      35835      20940   

   BILL_AMT5  BILL_AMT6  PAY_AMT1  PAY_AMT2  PAY_AMT3  PAY_AMT4  PAY_AMT5  \
0          0          0         0       689         0         0         0   
1       3455       3261         0      1000      1000      1000         0   
2      14948      15549      1518      1500      1000      1000      1000   
3      28959      29547      2000      2019      1200      1100      1069   
4      19146      19131      2000     36681     10000      9000       689   

   PAY_AMT6  default payment next month  
0         0                           1  
1      2000                           1  
2      5000                           0  
3      1000                           0  
4       679                           0

In [5]:
np.random.seed(seed=24)


In [6]:
random_integers = np.random.randint(low=1,high=5,size=100)
random_integers

array([3, 4, 1, 4, 2, 2, 2, 1, 4, 4, 1, 4, 4, 3, 4, 4, 4, 4, 4, 4, 2, 3,
       4, 4, 2, 4, 2, 4, 1, 1, 3, 1, 4, 2, 2, 1, 4, 3, 2, 2, 3, 3, 2, 3,
       4, 2, 3, 4, 1, 3, 4, 2, 2, 4, 1, 2, 3, 3, 2, 1, 2, 4, 2, 1, 4, 3,
       1, 2, 1, 3, 4, 2, 3, 4, 1, 3, 2, 1, 1, 3, 3, 4, 3, 2, 4, 1, 4, 4,
       4, 4, 1, 4, 3, 2, 4, 4, 3, 3, 2, 4])

In [7]:
is_equal_to_3 = random_integers == 3
is_equal_to_3

array([ True, False, False, False, False, False, False, False, False,
       False, False, False, False,  True, False, False, False, False,
       False, False, False,  True, False, False, False, False, False,
       False, False, False,  True, False, False, False, False, False,
       False,  True, False, False,  True,  True, False,  True, False,
       False,  True, False, False,  True, False, False, False, False,
       False, False,  True,  True, False, False, False, False, False,
       False, False,  True, False, False, False,  True, False, False,
        True, False, False,  True, False, False, False,  True,  True,
       False,  True, False, False, False, False, False, False, False,
       False, False,  True, False, False, False,  True,  True, False,
       False])

In [8]:
is_equal_to_3[:5]


array([ True, False, False, False, False])

In [9]:
sum(is_equal_to_3)


22

In [10]:
random_integers[is_equal_to_3]


array([3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

In [11]:
id_counts = df['ID'].value_counts()
id_counts

0ad143f2-bd95    2
f11c5e51-a535    2
85bd7f39-2e9b    2
02e41927-a6df    2
c5368117-b498    2
97d1d2eb-c72f    2
0a2d6db4-0c54    2
e77f7765-8731    2
dab579ee-1645    2
693a0664-bde6    2
83d174e1-5f9a    2
05009844-7be8    2
af052d9b-f06b    2
e8037410-5cd0    2
c9826d63-f7d3    2
590a776e-5049    2
c5a658d0-92da    2
42009c72-651f    2
379e0b03-4ca0    2
7574bf9e-f3f9    2
f6032812-464e    2
bbf202ae-a964    2
80282ca6-96a6    2
5f38afd8-e138    2
5f483bdb-3aaf    2
8d3a2576-a958    2
2a793ecf-05c6    2
fa286931-8ded    2
1a055566-c187    2
d9dafe9c-b497    2
                ..
1bce6b2e-5c88    1
36f5dd00-86ec    1
33e4bcc6-fd39    1
90da01fe-1f02    1
f32fc941-2bc9    1
9250324e-4143    1
15099435-fbb5    1
62a3dfc8-65dd    1
0c418408-5c53    1
4ed4f75c-248c    1
85b1ec66-f338    1
dc360f9e-dd2c    1
d8a4d0ac-d873    1
37126c60-b089    1
818f49be-9c35    1
658388b7-fe45    1
94371728-181f    1
fd11c49d-1277    1
069ee06b-ea27    1
99e53785-a51c    1
cca90671-5a11    1
13d62392-c05

In [12]:
dupe_mask = id_counts == 2
dupe_mask[0:5]

0ad143f2-bd95    True
f11c5e51-a535    True
85bd7f39-2e9b    True
02e41927-a6df    True
c5368117-b498    True
Name: ID, dtype: bool

In [13]:
dupe_ids = id_counts.index[dupe_mask]
dupe_ids

Index(['0ad143f2-bd95', 'f11c5e51-a535', '85bd7f39-2e9b', '02e41927-a6df',
       'c5368117-b498', '97d1d2eb-c72f', '0a2d6db4-0c54', 'e77f7765-8731',
       'dab579ee-1645', '693a0664-bde6',
       ...
       '04c32736-903c', '47d9ee33-0df0', 'fd6033f4-cc72', 'f31d1048-5fa9',
       'b557f3c2-ebec', 'a7e199e1-2c44', 'a17f0f1f-d9f6', '69566a6b-6156',
       '4cb27699-fe3f', '5edb4d2b-067c'],
      dtype='object', length=313)

In [14]:
dupe_ids = list(dupe_ids)
len(dupe_ids)

313

In [15]:
df.loc[df['ID'].isin(dupe_ids[0:3]),:].head(10) 


ID  LIMIT_BAL  SEX  EDUCATION  MARRIAGE  AGE PAY_1  PAY_2  \
4576   04c32736-903c      90000    2          1         2   29     1     -1   
4676   04c32736-903c          0    0          0         0    0     0      0   
5753   823267c1-561b     330000    2          2         2   30    -2     -2   
5853   823267c1-561b          0    0          0         0    0     0      0   
21274  693a0664-bde6      50000    1          3         2   51     1     -2   
21374  693a0664-bde6          0    0          0         0    0     0      0   

       PAY_3  PAY_4  ...  BILL_AMT4  BILL_AMT5  BILL_AMT6  PAY_AMT1  PAY_AMT2  \
4576      -1     -2  ...          0          0          0       194         0   
4676       0      0  ...          0          0          0         0         0   
5753      -2     -2  ...          0          0          0         0         0   
5853       0      0  ...          0          0          0         0         0   
21274     -2     -2  ...          0          0          0         0         0   
21374      0      0  ...          0          0          0         0         0   

       PAY_AMT3  PAY_AMT4  PAY_AMT5  PAY_AMT6  default payment next month  
4576          0         0         0       217                           0  
4676          0         0         0         0                           0  
5753          0         0         0         0                           1  
5853          0         0         0         0                           0  
21274         0         0         0         0                           1  
21374         0         0         0         0                           0  

[6 rows x 25 columns]

In [15]:
df_zero_mask = df == 0
df_zero_mask

ID  LIMIT_BAL    SEX  EDUCATION  MARRIAGE    AGE  PAY_1  PAY_2  \
0      False      False  False      False     False  False  False  False   
1      False      False  False      False     False  False  False  False   
2      False      False  False      False     False  False   True   True   
3      False      False  False      False     False  False   True   True   
4      False      False  False      False     False  False  False   True   
5      False      False  False      False     False  False   True   True   
6      False      False  False      False     False  False   True   True   
7      False      False  False      False     False  False   True  False   
8      False      False  False      False     False  False   True   True   
9      False      False  False      False     False  False  False  False   
10     False      False  False      False     False  False   True   True   
11     False      False  False      False     False  False  False  False   
12     False      False  False      False     False  False  False   True   
13     False      False  False      False     False  False  False  False   
14     False      False  False      False     False  False   True   True   
15     False      False  False      False     False  False  False  False   
16     False      False  False      False     False  False   True   True   
17     False      False  False      False     False  False  False   True   
18     False      False  False      False     False  False  False  False   
19     False      False  False      False     False  False  False  False   
20     False      False  False      False     False  False   True   True   
21     False      False  False      False     False  False  False  False   
22     False      False  False      False     False  False  False   True   
23     False      False  False      False     False  False  False  False   
24     False      False  False      False     False  False   True   True   
25     False      False  False      False     False  False   True   True   
26     False      False  False      False     False  False  False  False   
27     False      False  False      False     False  False   True   True   
28     False      False  False      False     False  False  False  False   
29     False      False  False      False     False  False  False   True   
...      ...        ...    ...        ...       ...    ...    ...    ...   
29970  False      False  False      False     False  False  False  False   
29971  False      False  False      False     False  False   True   True   
29972  False      False  False      False     False  False   True   True   
29973  False      False  False      False     False  False  False  False   
29974  False      False  False      False     False  False  False  False   
29975  False       True   True       True      True   True   True   True   
29976  False      False  False      False     False  False  False  False   
29977  False      False  False      False     False  False   True   True   
29978  False      False  False      False     False  False   True   True   
29979  False      False  False      False     False  False  False  False   
29980  False      False  False      False     False  False   True   True   
29981  False      False  False      False     False  False  False  False   
29982  False      False  False      False     False  False   True   True   
29983  False      False  False      False     False  False  False  False   
29984  False      False  False      False     False  False  False  False   
29985  False      False  False      False     False  False  False  False   
29986  False      False  False      False     False  False  False  False   
29987  False      False  False      False     False  False   True   True   
29988  False      False  False      False     False  False   True   True   
29989  False      False  False      False     False  False  False  False   
29990  False      False  False      False     False  False

In [16]:
feature_zero_mask = df_zero_mask.iloc[:,1:].all(axis=1)
sum(feature_zero_mask)


315

In [17]:
df_clean_1 = df.loc[~feature_zero_mask,:].copy()


In [18]:
df_clean_1['ID'].nunique()


29685

In [19]:
valid_pay_1_mask = df_clean_1['PAY_1'] != 'Not available'
valid_pay_1_mask[0:5]

0    True
1    True
2    True
3    True
4    True
Name: PAY_1, dtype: bool

In [20]:
df_clean_2 = df_clean_1.loc[valid_pay_1_mask,:].copy()


In [21]:
df_clean_2['PAY_1'] = df_clean_2['PAY_1'].astype('int64')
df_clean_2[['PAY_1', 'PAY_2']].info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 26664 entries, 0 to 29999
Data columns (total 2 columns):
PAY_1    26664 non-null int64
PAY_2    26664 non-null int64
dtypes: int64(2)
memory usage: 624.9 KB


In [22]:
df_clean_2['EDUCATION'].replace(to_replace=[0, 5, 6], value=4, inplace=True)
df_clean_2['EDUCATION'].value_counts()

2    12458
1     9412
3     4380
4      414
Name: EDUCATION, dtype: int64

In [23]:
df_clean_2['MARRIAGE'].replace(to_replace=0, value=3, inplace=True)
df_clean_2['MARRIAGE'].value_counts()

2    14158
1    12172
3      334
Name: MARRIAGE, dtype: int64

In [24]:
df_clean_2['EDUCATION_CAT'] = 'none'


In [25]:
df_clean_2[['EDUCATION', 'EDUCATION_CAT']].head(10)


EDUCATION EDUCATION_CAT
0          2          none
1          2          none
2          2          none
3          2          none
4          2          none
5          1          none
6          1          none
7          2          none
8          3          none
9          3          none

In [26]:
cat_mapping = {
    1: "graduate school",
    2: "university",
    3: "high school",
    4: "others"
}

In [27]:
df_clean_2['EDUCATION_CAT'] = df_clean_2['EDUCATION'].map(cat_mapping)
df_clean_2[['EDUCATION', 'EDUCATION_CAT']].head(10)

EDUCATION    EDUCATION_CAT
0          2       university
1          2       university
2          2       university
3          2       university
4          2       university
5          1  graduate school
6          1  graduate school
7          2       university
8          3      high school
9          3      high school

In [28]:
edu_ohe = pd.get_dummies(df_clean_2['EDUCATION_CAT'])
edu_ohe.head(10)
df_with_ohe = pd.concat([df_clean_2, edu_ohe], axis=1)
df_with_ohe[['EDUCATION_CAT', 'graduate school',
             'high school', 'university', 'others']].head(10)
df_with_ohe.to_csv('cleaned_data.csv', index=False)
